config:
  # Allow inline HTML (common in READMEs for badges, etc.)
  MD033: false
  # Allow duplicate headings in different sections
  MD024:
    siblings_only: true
  # Allow long lines (code examples, URLs)
  MD013: false
  # Allow trailing punctuation in headings
  MD026: false
  # Allow compact table style (no spaces around pipes)
  MD060: false
  # Allow fenced code blocks without language specifier
  MD040: false

ignores:
  - "NOTES.md"
