name: Semver GoArg

on:
  create:
  push:
    branches:
      - 'goarg/v[0-9]+.[0-9]+'
    paths:
      - 'goarg/**'

jobs:
  semver:
    uses: ./.github/workflows/semver.yml
    permissions:
      contents: write
    with:
      prefix: 'goarg/v'
      ref-pattern: 'refs/heads/goarg/v'
