name: Semver OptArgs

on:
  create:
  push:
    branches:
      - 'v[0-9]+.[0-9]+'
    paths-ignore:
      - '.github/**'
      - 'goarg/**'
      - 'pflags/**'

jobs:
  semver:
    uses: ./.github/workflows/semver.yml
    permissions:
      contents: write
    with:
      prefix: 'v'
      ref-pattern: 'refs/heads/v'

  release:
    needs: semver
    if: needs.semver.outputs.tag != ''
    uses: ./.github/workflows/release.yml
    permissions:
      contents: write
    with:
      tag: ${{ needs.semver.outputs.tag }}
